name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6 12 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        curl https://data.nola.gov/api/id/2jgv-pqrq.json | jq . > 311calls.json
        curl "https://data.nola.gov/api/id/2jgv-pqrq.json?request_reason=Pothole&$order=:id%20DESC" | jq . > potholes.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
